config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get 'pages/home', to: 'pages#home'
  get '/about', to: 'pages#about'

  resources :posts do
    member do
      get "delete", to: 'posts#delete' 
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :name, presence: true 
    validates :description, presence: true, length: {minimum:35, maximum:500}
    belongs_to :user
    validates :user_id, presence: true
end

app/models/todo.rb
class Todo < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true

    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: {maximum:30}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum:255}, 
                      format: {with: VALID_EMAIL_REGEX},
                      uniqueness: {case_sensitive: false}
    has_many :posts                  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
        
    end

    def about
        
    end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: [:show, :update, :edit]
    def index
        @posts = Post.all
    end

    def show 
    end
    def new
        @post = Post.new
    end
    
    def create
        @post = Post.new(post_params)
        @post.user = User.first
        if @post.save
            flash[:info] = "Post criado com sucesso"
            redirect_to  post_path(@post)
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @post.update(post_params)
            flash[:success] = "Post atualizado com sucesso"
            redirect_to post_path(@post)
        else
            render 'edit'
        end
    end

    def delete
        Post.find(params[:id]).destroy
        flash[:success] = "post deleted successfully"
        redirect_to posts_path
    end

    private 
        def set_post
            @post = Post.find(params[:id]) 
        end
        def post_params
            params.require(:post).permit(:name, :description)
        end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    before_action :set_todo, only: [:edit, :update, :show, :destroy]
    
    def new
        @todo = Todo.new
    end
    def create
        @todo = Todo.new(todo_params)
        if @todo.save
            flash[:notice] = "Todo criado com sucesso"
            redirect_to  todo_path(@todo)
        else
            render 'new'
        end
    end

    def show

    end

    def edit
   
    end

    def update
        if @todo.update(todo_params)
            flash[:notice] = "Todo Atualizado"
            redirect_to  todo_path(@todo)
        else
            render 'edit'
        end
    end

    def index
        @todos = Todo.all
    end

    def destroy
        @todo.destroy
        flash[:notice] = "Todo Excluido"
        redirect_to todos_path
    end

    private 
        def set_todo
            @todo = Todo.find(params[:id])
        endfv0    
        end
        def todo_params
            params.require(:todo).permit(:name, :description)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = {size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "http://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "rounded-circle")
    end
end

app/views/layouts/_messages.html.erb
<div class= "row">
    <div class= "col-md-6 offset-md-3 center">
        <% flash.each do |name, msg|%>
           <div class= "alert alert-<%=name%>", role="alert">
                <a href= "#" class= "close" data-dismiss= "alert">&#215;</a>
                <%= msg%>                
           </div>
        <% end %>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
   <%= link_to "nUvEm", root_path, class: "navbar", id: "logo"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Posts
        </a>
        <ul class="dropdown-menu">
          <li class="dropdown-item"> <%= link_to "Criar Post", new_post_path %> </li>
          <div class="dropdown-divider"></div>
        </ul>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Receitinhas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> 
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class= "container">
      <%= yield %>
    </div>
  </body>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</html>

app/views/pages/about.html.erb
<h1>this is the about page</h1>

app/views/pages/home.html.erb
<div class="jumbontron center">
  <h1>@@@@ Faça Parte da Comunidade @@@@@</h1>
  <p><%= link_to " Ver todos os Posts ", posts_path, class: "btn btn-dark btn-lg", id:"botaoLogin"  %></p>
     
  <div class="row">
    <div class="col-lg-4">
      <h4>Safari bug warning!</h4>
      <p class="text-danger">As of v9.1.2, Safari exhibits a bug in which resizing your browser horizontally causes rendering errors in the justified nav that are cleared upon refreshing.</p>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      <p><%= link_to " Leia ", "#", class: "btn btn-light btn-small" %></p>
    </div>
    <div class="col-lg-4">
      <h4>Heading</h4>
      <p>MARCHELOOOW </p>
      <p><%= link_to " Leia ", "#", class: "btn btn-light btn-small" %></p>
    </div>
    <div class="col-lg-4">
      <h4>Heading</h4>
      <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
      <p><%= link_to " Leia ", "#", class: "btn btn-light btn-small" %></p>
    </div>
  </div>
</div>

app/views/posts/_form.html.erb
<%= render 'shared/errors', obj: @post %>
<div class= row>
    <div class= col-md-16>
        <%= form_for(@post, :html => {class: "form-horizontal", role: "form"}) do |f| %>
            <div class = "form_group col-md-6 offset-md-3 center">
                    <%= f.label :name %>
                    <%= f.text_field :name, class: "form-control", placeholder: "Nome do Post", autofocus: true %>
            </div>
            <div class = "form_group col-md-6 offset-md-3 center">
                    <%= f.label :description %>
                    <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Descrição do Post", autofocus: true %>
            </div>
            <div class = "form_group  center">
                <%= f.submit class: "btn btn-dark btn-lg", id:"botaoLogin" %>
        <% end %>
        <div class= "colormatch center">
           [[<%= link_to "cancelar", posts_path %>]]
        </div>
    </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/page_title', title: "Editando o Post" %>
<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'shared/page_title', title: "Posts" %>

<% @posts.each do |post| %>
    <div class= "row">
        <div class= "col-md-2">
            <section class="center">
                <%= gravatar_for(post.user, size:90) %>
            </section>
        </div>
        <div class="col-md-8 well">
            <h4><%= link_to post.name, post_path(post) %></h4>
            <p><%= truncate(post.description, length: 150) %></p>
            <p>
                <span class="quiet"><small>Created <%= time_ago_in_words(post.created_at) %> ago</small></span>
            </p>
        </div>
    </div>
<%end%>

app/views/posts/new.html.erb
<%= render 'shared/page_title', title: "Novo Post" %>
<%= render 'form' %>

app/views/posts/show.html.erb
<%= render 'shared/page_title', title: @post.name %>

<div class="well col-md-12 col-md-offset-2">
    <h3><strong>Description:</strong></h3>
    <%= simple_format(@post.description)  %>
    <p>
        <div class= "float-right">
            <p> Created by: </p>
            <%= link_to gravatar_for(@post.user), posts_path %>
            <p> <%= @post.user.name.capitalize %></p>
            <p>  Created: <%= time_ago_in_words(@post.created_at)%> ago</p>
         </div>
    </p>
    <div class= "post-actions">
            <%= link_to "Editar", edit_post_path(@post), class: "btn btn-dark btn-sm" %>
            <%= link_to "Delete", delete_post_path(@post), data: { confirm: "Are you sure you want to delete?", method: :delete },
                                                           class: "btn btn-sm btn-danger" %>
            <%= link_to "Voltar", posts_path, class: "btn btn-dark btn-sm" %>
    </div>  
    </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-md-6 offset-md-3 center">
      <div class="card text-white bg-danger mb-3">
        <div class="card-heading">
            <%= pluralize(obj.errors.count, "error") %>
            <%= obj.class %>:
            <div class="card-body">
                <ul>
                    <% obj.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                </ul>
            </div>
        </div>  
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_page_title.html.erb
<h1 align="center"><%= title.capitalize %></h1>
<hr />

app/views/todos/_form.html.erb
<% if @todo.errors.any? %>
    <h2>Informações necessarias não preenchidas</h2>
    <ul>
        <% @todo.errors.full_messages.each do |msg| %>
        <li> <%= msg %></li>
        <% end %>
    </ul>
<% end %>

<%= form_for @todo do |f| %>
 <p>
     <%= f.label :name %> <br>
     <%= f.text_field :name %>
 </p>

 <p>
    <%= f.label :description %> <br>
    <%= f.text_area :description %>
 </p>

 <p>
    <%= f.submit %>
 </p>

<% end %>
<%= link_to "Back", todos_path %>

app/views/todos/edit.html.erb
<h1>Editando um Todo</h1>


<%= render 'form' %>

app/views/todos/index.html.erb
<h1>Listando Todos os Todos</h1>

<p>
    <%= link_to "Create a Todo", new_todo_path %>
</p>

<table>
    <tr>
        <th>Name</th>
        <th>Description</th>
    </tr>
    <% @todos.each do |todo| %>
        <tr>
            <td><%= todo.name %></td>
            <td><%= todo.description %></td>
            <td><%= link_to "Edit", edit_todo_path(todo) %></td>
            <td><%= link_to "Show", todo_path(todo) %></td>
            <td><%= link_to "Delete", todo_path(todo), method: :delete, data: {confirm: "Deseja Excluir?"} %></td>
        </tr>
    <% end %>
</table>

app/views/todos/new.html.erb
<h1>create a new</h1>
<%= render 'form' %>

app/views/todos/show.html.erb
<h1>Showing a Todo</h1>
<p>
    name: <%= @todo.name %>
</p>
<p>
    description: <%= @todo.description %>
</p>
<%= link_to "Edit", edit_todo_path(@todo) %>
<%= link_to "Back", todos_path %>